# Generated by Django 4.1.6 on 2023-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='text2',
            field=models.TextField(),
        ),
    ]
