# Generated by Django 4.1.6 on 2023-12-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_text1_alter_about_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='review',
            field=models.TextField(max_length=250),
        ),
    ]
