# Generated by Django 4.1.6 on 2023-12-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_testimonial_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
